### ISSUE TITLE
Issue with Carla

### ISSUE THREAD

**Issue by erwan35** [sjaehn/BSlizr#4]
Hello,

I have successfully build your software, it's running fine when I run it with jalv.gtk but not on Carla 1.9.13+2.0-RC3.

Nothing seems to be happening. The monitor is not "moving" even if it's switched on.

Do you think of anything that I might be doing wrong ?

Cheers
Erwan

**Comment by sjaehn** [comment]
Hi erwan35,

yes, it's true in Carla's startup configuration. The cause is B.Slizr needs information about the position within a beat. And thus it needs Jack transport to be switched on.

To get it running, you have to activate Jack transport in Carla:
* Click on the "Transport" tab on the left side of Carla
* Mark "Use Jack transport"
* Click on the play button in the playback controls of this tab

Good luck!

**Comment by sjaehn** [comment]
Documentation updated (hint to Jack transport) in commit 8270272

**Comment by erwan35** [comment]
Thanks for your help !
Let's play now :)

Cheers
Erwan
